/* Core */
import { createSlice, type PayloadAction } from "@reduxjs/toolkit";

/* Instruments */
// import { incrementAsync } from "./thunks";

const initialState: CartSliceState = {
  value: [],
  status: "idle",
};

export const cartSlice = createSlice({
  name: "cart",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    addtocart: (state, action: PayloadAction<object>) => {
      state = { ...state, value: [...state.value, action.payload] };
    },
    decrementfromcart: (state, action: PayloadAction<object>) => {
      state = {
        ...state,
        value: [
          ...state.value.filter((item: object) => item !== action?.payload),
        ],
      };
    },

    // Use the PayloadAction type to declare the contents of `action.payload`
    // incrementByAmount: (state, action: PayloadAction<number>) => {
    //   state.value += action.payload;
    // },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: (builder) => {
  //   builder
  //     .addCase(incrementAsync.pending, (state) => {
  //       state.status = "loading";
  //     })
  //     // .addCase(incrementAsync.fulfilled, (state, action) => {
  //     //   state.status = "idle";
  //     //   state.value += action.payload;
  //     // });
  // },
});

/* Types */
export interface CartSliceState {
  value: object[];
  status: "idle" | "loading" | "failed";
}
